name: goodman_lamps
channels:
  - astroconda
dependencies:
  - qt
  - astropy
  - matplotlib==3.0.1
  - numpy
  - pandas==0.23.0
  - pip
  - scipy
  - pip:
      - pyqt5
      - ccdproc
      - coveralls
      - m2r
      - sphinx==1.6.3
      - sphinx_rtd_theme
      - sphinxcontrib.napoleon
      - goodman_pipeline==1.2.1.dev6
