name: goodman_lamps
channels:
  - astroconda
dependencies:
  - qt
  - astropy
  - matplotlib==2.1.0
  - numpy
  - pandas==0.23.0
  - pip
  - scipy
  - pip:
      - pyqt5
      - ccdproc
      - coveralls
      - m2r
      - sphinx
      - sphinxcontrib.napoleon
      - goodman_pipeline==1.2.1.dev6
