name: goodman_lamps_2
channels:
  - astroconda
dependencies:
  - qt
  - astropy
  - matplotlib
  - numpy
  - pandas==0.23.0
  - pip
  - scipy
  - pip:
      - pyqt5
      - ccdproc
      - coveralls
      - m2r
      - sphinx
      - sphinx_rtd_theme
      - sphinxcontrib.napoleon
      - goodman_pipeline
