name: goodman_focus
  channels:
    - astroconda
  dependencies:
    - astropy
    - matplotlib
    - numpy
    - pandas
    - pip
    - scipy
    - pip:
        - goodman_pipeline==1.2.0
        - ccdproc
        - coveralls
        - m2r
        - sphinx
        - sphinxcontrib.napoleon
